### ISSUE TITLE
Segmentation Fault running "./anntest weights.bin"

### ISSUE THREAD

**Issue by arunnura123** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#187]
I see the following segmentation Fault when I try running the anntest.

1.  Onnx model ( Googlenet ) is converted  to NNIR
2.  NNIR to Vx format using the python utilities  

./anntest weights.bin
OK: loaded 21 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx900) [OpenCL 1.2 ] [SvmCaps 0 1]
MIOpen Error: std::bad_alloc
ERROR: fatal error occured at /home/amd/Miopen-opencl/amdovx-modules/vx_nn/src/convolution_layer.cpp#200
Segmentation fault (core dumped)

Could you help me on what I am missing

Thanks,
Arun

**Comment by rgiduthuri** [comment]
Can you share the onnx model that you’re using?

**Comment by arunnura123** [comment]
I am using https://github.com/onnx/models/tree/master/bvlc_googlenet 
16GB Memory . I will try uninstalling rocm and rebuilding again.

Thanks

**Comment by arunnura123** [comment]
This issue seems to be resolved after I installed "apt-get install miopen-opencl" instead of building from source.
